### ISSUE TITLE
FreeBSD: with one name change all tests pass

### ISSUE THREAD

**Issue by bakul** [cmh25/gk#2]
Unfortunately FreeBSD defines kcmp() in its standard library which conflicts with the gk's function of the same name. Once the local function is renamed, all tests pass, including testv.sh. Great job!

**Comment by cmh25** [comment]
This is great news. Thanks for letting me know about this. I'll rename kcmp() so this works on FreeBSD.

**Comment by cmh25** [comment]
kcmp() has been changed to kcmpr(). Thanks again.
